<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJcExDD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJcExDD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHJcExDD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHJcExDD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHJcExDD\App_KernelDevDebugContainer([
    'container.build_hash' => 'HJcExDD',
    'container.build_id' => '874e58ce',
    'container.build_time' => 1637674523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJcExDD');
